### ISSUE TITLE
ValueError: Too many dimensions: 3 > 2.

### ISSUE THREAD

**Issue by Dylanhj** [floatlazer/semantic_slam#27]
I use Ade20K dataset to train model. This error occurred.
Original Traceback (most recent call last):
  File "/home/docker/.local/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/docker/.local/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/docker/catkin_ws/src/semantic_slam/semantic_cloud/include/ptsemseg/loader/ade20k_loader.py", line 43, in __getitem__
    img, lbl = self.augmentations(img, lbl)
  File "/home/docker/catkin_ws/src/semantic_slam/semantic_cloud/include/ptsemseg/augmentations.py", line 16, in __call__
    img, mask = Image.fromarray(img, mode='RGB'), Image.fromarray(mask, mode='L')
  File "/home/docker/.local/lib/python2.7/site-packages/PIL/Image.py", line 2657, in fromarray
    raise ValueError("Too many dimensions: %d > %d." % (ndim, ndmax))
ValueError: Too many dimensions: 3 > 2.

**Comment by Dylanhj** [comment]
https://github.com/meetshah1995/pytorch-semseg/issues/88
